# Date: 12/22/15
# Maintainer: Brandon B. Jozsa
# Purpose: Updated/Upgraded Ubuntu Image (Trusty)
FROM ubuntu:14.04
MAINTAINER Brandon B. Jozsa <bjozsa@jinkit.com>

# Update and Install Prerequisites
RUN apt-get update && apt-get upgrade -y

# Get in, get out
CMD ["/bin/bash"]
